In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print("Project Root:", PROJECT_ROOT)

Project Root: /Users/dhairyas87/Documents/Projects/explainable-credit-risk-management/xai-credit-risk-freddie-mac

# Model Training

## Objective

This notebook develops predictive models for borrower financial stress.

The objectives are:

- Build a baseline model using traditional mortgage origination features
- Build a BSS-enhanced model using the proposed Borrower Serviceability Score framework
- Compare predictive performance
- Evaluate whether BSS provides incremental predictive value

This notebook begins with a Logistic Regression benchmark model before moving to more advanced machine learning techniques.

In [2]:
import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from src.preprocessing import (
    prepare_xy,
    build_preprocessor
)

# Load Modeling Datasets

The baseline feature store contains traditional mortgage origination characteristics and excludes the proposed BSS framework.

Temporal split:

- Train = 2018Q1 + 2018Q2
- Validation = 2018Q3
- Test = 2018Q4

In [3]:
train_df = pd.read_parquet(
    "../data/modeling/train_baseline.parquet"
)

valid_df = pd.read_parquet(
    "../data/modeling/valid_baseline.parquet"
)

test_df = pd.read_parquet(
    "../data/modeling/test_baseline.parquet"
)

print(train_df.shape)
print(valid_df.shape)
print(test_df.shape)

(661318, 35)
(336669, 35)
(287447, 35)

# Create Features and Target

The preprocessing utility performs:

- Leakage removal
- Metadata removal
- Constant feature removal
- Date feature engineering

The output consists of:

- X = predictor variables
- y = stress_flag

In [4]:
X_train, y_train = prepare_xy(
    train_df
)

X_valid, y_valid = prepare_xy(
    valid_df
)

X_test, y_test = prepare_xy(
    test_df
)

print(X_train.shape)
print(X_valid.shape)
print(X_test.shape)

(661318, 24)
(336669, 24)
(287447, 24)

# Build Preprocessing Pipeline

Machine learning models require numerical input.

The preprocessing pipeline performs:

Numerical Features:
- Median imputation
- Standard scaling

Categorical Features:
- Most frequent imputation
- One-hot encoding

The preprocessing pipeline is fitted only on the training dataset to prevent information leakage.

In [5]:
preprocessor = build_preprocessor()

In [6]:
preprocessor.fit(
    X_train
)

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['credit_score', 'mortgage_insurance_pct',
                                  'num_units', 'cltv', 'dti', 'original_upb',
                                  'ltv', 'interest_rate', 'original_loan_term',
                                  'num_borrowers', 'remaining_term_months']),
                                ('categorical',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['msa', 'first_time_homebuyer_indicator',
                                  'occupancy_status', 'channel',
                                  'property_state', 'property_type',
                                  'loan_purpose', 'seller_name',
                                  'servicer_name', 'super_conforming_flag',
                                  'program_indicator', 'harp_indicator',
                                  'mortgage_insurance_cancellation_indicator'])])

# Transform Datasets

After fitting the preprocessing pipeline, all datasets are transformed into model-ready numerical representations.

These transformed matrices will be used for Logistic Regression training.

In [7]:
X_train_processed = (
    preprocessor.transform(
        X_train
    )
)

X_valid_processed = (
    preprocessor.transform(
        X_valid
    )
)

X_test_processed = (
    preprocessor.transform(
        X_test
    )
)

print(
    X_train_processed.shape
)

print(
    X_valid_processed.shape
)

print(
    X_test_processed.shape
)

(661318, 587)
(336669, 587)
(287447, 587)

In [8]:
X_train_processed

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15871632 stored elements and shape (661318, 587)>

In [9]:
feature_names = (
    preprocessor
    .get_feature_names_out()
)

len(feature_names)

587

In [10]:
pd.Series(
    feature_names
).value_counts().head()

numeric__credit_score              1
numeric__mortgage_insurance_pct    1
numeric__num_units                 1
numeric__cltv                      1
numeric__dti                       1
Name: count, dtype: int64

In [11]:
pd.Series(
    feature_names
).sample(20)

289                             categorical__msa_34980.0
239                             categorical__msa_30020.0
478                       categorical__property_state_GA
34                              categorical__msa_12220.0
514                       categorical__property_state_UT
526                        categorical__property_type_SF
317                             categorical__msa_37764.0
488                       categorical__property_state_MA
426                             categorical__msa_47220.0
265                             categorical__msa_32820.0
333                             categorical__msa_39150.0
556    categorical__servicer_name_AURORA FINANCIAL GR...
44                              categorical__msa_13140.0
505                       categorical__property_state_OK
374                             categorical__msa_42060.0
136                             categorical__msa_21340.0
563    categorical__servicer_name_LAKEVIEW LOAN SERVI...
110                             categorical__msa_19140.0
8                            numeric__original_loan_term
35                              categorical__msa_12260.0
dtype: str

In [12]:
feature_names = preprocessor.get_feature_names_out()

[
    f
    for f in feature_names
    if "super_conforming_flag" in f
][:20]

['categorical__super_conforming_flag_Y']

In [13]:
[
    f
    for f in feature_names
    if "program_indicator" in f
][:20]

['categorical__program_indicator_9',
 'categorical__program_indicator_F',
 'categorical__program_indicator_H']

In [14]:
[
    f
    for f in feature_names
    if "interest_only_indicator" in f
][:20]

[]

In [15]:
for col in [
    "super_conforming_flag",
    "program_indicator",
    "harp_indicator",
    "interest_only_indicator",
    "mortgage_insurance_cancellation_indicator"
]:
    print("\n", col)

    print(
        train_df[col]
        .value_counts(dropna=False)
        .head(20)
    )

 super_conforming_flag
super_conforming_flag
NaN    639733
Y       21585
Name: count, dtype: int64

 program_indicator
program_indicator
9    586551
H     71625
F      3142
Name: count, dtype: int64

 harp_indicator
harp_indicator
NaN    652655
Y        8663
Name: count, dtype: int64

 interest_only_indicator
interest_only_indicator
N    661318
Name: count, dtype: int64

 mortgage_insurance_cancellation_indicator
mortgage_insurance_cancellation_indicator
7    449033
N    183580
Y     28705
Name: count, dtype: int64

In [16]:
X_train, y_train = prepare_xy(train_df)

preprocessor.fit(X_train)

X_train_processed = preprocessor.transform(X_train)

print(X_train_processed.shape)

(661318, 587)

In [17]:
len(
    preprocessor.get_feature_names_out()
)

587

In [18]:
[
    f
    for f in preprocessor.get_feature_names_out()
    if "vantagescore" in f.lower()
]

[]

In [19]:
[
    f
    for f in preprocessor.get_feature_names_out()
    if "servicer_name" in f
][:10]

['categorical__servicer_name_AMERIHOME MORTGAGE COMPANY, LLC',
 'categorical__servicer_name_AURORA FINANCIAL GROUP, INC.',
 'categorical__servicer_name_CALIBER HOME LOANS, INC.',
 'categorical__servicer_name_CITIZENS BANK, NA',
 'categorical__servicer_name_FIFTH THIRD BANK, NATIONAL ASSOCIATION',
 'categorical__servicer_name_FREEDOM MORTGAGE CORPORATION',
 'categorical__servicer_name_HOME POINT FINANCIAL CORPORATION',
 'categorical__servicer_name_JPMORGAN CHASE BANK, NATIONAL ASSOCIATION',
 'categorical__servicer_name_LAKEVIEW LOAN SERVICING, LLC',
 'categorical__servicer_name_MATRIX FINANCIAL SERVICES CORPORATION']

In [20]:
[
    f
    for f in preprocessor.get_feature_names_out()
    if "program_indicator" in f
]

['categorical__program_indicator_9',
 'categorical__program_indicator_F',
 'categorical__program_indicator_H']

# Baseline Logistic Regression

A Logistic Regression model is used as the initial benchmark for borrower stress prediction.

Reasons for selection:

- Interpretable
- Computationally efficient
- Widely used in credit risk modelling
- Provides a strong baseline before evaluating more complex machine learning models

Class imbalance is addressed using class weighting.

In [21]:
from sklearn.linear_model import LogisticRegression

In [26]:
log_reg = LogisticRegression(
    class_weight="balanced",
    max_iter=2000,
    random_state=42
)

log_reg.fit(
    X_train_processed,
    y_train
)

LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)

In [27]:
valid_pred = log_reg.predict(
    X_valid_processed
)

valid_prob = log_reg.predict_proba(
    X_valid_processed
)[:, 1]

In [28]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = pd.DataFrame({

    "Metric": [

        "Accuracy",
        "Precision",
        "Recall",
        "F1",
        "ROC-AUC"
    ],

    "Value": [

        accuracy_score(
            y_valid,
            valid_pred
        ),

        precision_score(
            y_valid,
            valid_pred
        ),

        recall_score(
            y_valid,
            valid_pred
        ),

        f1_score(
            y_valid,
            valid_pred
        ),

        roc_auc_score(
            y_valid,
            valid_prob
        )
    ]
})

results

      Metric     Value
0   Accuracy  0.665580
1  Precision  0.241182
2     Recall  0.668238
3         F1  0.354439
4    ROC-AUC  0.727588

In [29]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_valid,
    valid_pred
)

cm

array([[193172,  97244],
       [ 15345,  30908]])

In [30]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_valid,
        valid_pred
    )
)

              precision    recall  f1-score   support

           0       0.93      0.67      0.77    290416
           1       0.24      0.67      0.35     46253

    accuracy                           0.67    336669
   macro avg       0.58      0.67      0.56    336669
weighted avg       0.83      0.67      0.72    336669

In [31]:
feature_names = (
    preprocessor.get_feature_names_out()
)

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": log_reg.coef_[0]
})

coef_df = coef_df.sort_values(
    "coefficient",
    ascending=False
)

coef_df.head(20)

                                               feature  coefficient
479                     categorical__property_state_GU     1.389173
31                            categorical__msa_12054.0     1.147969
540  categorical__seller_name_HOME POINT FINANCIAL ...     1.063946
232                           categorical__msa_29484.0     1.026688
28                            categorical__msa_11694.0     0.936406
576             categorical__servicer_name_TRUIST BANK     0.921649
554    categorical__seller_name_WELLS FARGO BANK, N.A.     0.879716
140                           categorical__msa_21780.0     0.860439
575  categorical__servicer_name_SPECIALIZED LOAN SE...     0.851754
407                           categorical__msa_45294.0     0.811437
574    categorical__servicer_name_ROCKET MORTGAGE, LLC     0.807553
262                           categorical__msa_31924.0     0.804898
229                           categorical__msa_29414.0     0.756682
434                           categorical__msa_47764.0     0.696439
237                           categorical__msa_29820.0     0.628776
532  categorical__seller_name_CALIBER HOME LOANS, INC.     0.623215
94                            categorical__msa_17410.0     0.605225
267                           categorical__msa_33124.0     0.597325
480                     categorical__property_state_HI     0.595878
219                           categorical__msa_28740.0     0.586403

In [32]:
coef_df[
    coef_df["feature"].str.contains(
        "credit_score"
    )
]

                 feature  coefficient
0  numeric__credit_score     -0.56512

In [33]:
coef_df[
    coef_df["feature"].str.contains(
        "dti"
    )
]

        feature  coefficient
4  numeric__dti     0.206243

In [34]:
coef_df[
    coef_df["feature"].str.contains(
        "ltv"
    )
]

         feature  coefficient
3  numeric__cltv      0.30058
6   numeric__ltv     -0.24528

In [35]:
coef_importance = pd.DataFrame({
    "feature": feature_names,
    "coefficient": log_reg.coef_[0]
})

coef_importance["abs_coef"] = (
    coef_importance["coefficient"]
    .abs()
)

coef_importance.sort_values(
    "abs_coef",
    ascending=False
).head(30)

                                               feature  coefficient  abs_coef
572      categorical__servicer_name_QUICKEN LOANS INC.    -1.940015  1.940015
479                     categorical__property_state_GU     1.389173  1.389173
31                            categorical__msa_12054.0     1.147969  1.147969
540  categorical__seller_name_HOME POINT FINANCIAL ...     1.063946  1.063946
232                           categorical__msa_29484.0     1.026688  1.026688
28                            categorical__msa_11694.0     0.936406  0.936406
576             categorical__servicer_name_TRUIST BANK     0.921649  0.921649
561  categorical__servicer_name_HOME POINT FINANCIA...    -0.880132  0.880132
554    categorical__seller_name_WELLS FARGO BANK, N.A.     0.879716  0.879716
140                           categorical__msa_21780.0     0.860439  0.860439
557  categorical__servicer_name_CALIBER HOME LOANS,...    -0.852206  0.852206
575  categorical__servicer_name_SPECIALIZED LOAN SE...     0.851754  0.851754
549   categorical__seller_name_SUNTRUST MORTGAGE, INC.    -0.840274  0.840274
70                            categorical__msa_15540.0    -0.824833  0.824833
407                           categorical__msa_45294.0     0.811437  0.811437
531  categorical__seller_name_BRANCH BANKING & TRUS...    -0.810222  0.810222
574    categorical__servicer_name_ROCKET MORTGAGE, LLC     0.807553  0.807553
262                           categorical__msa_31924.0     0.804898  0.804898
229                           categorical__msa_29414.0     0.756682  0.756682
434                           categorical__msa_47764.0     0.696439  0.696439
21                            categorical__msa_11180.0    -0.638062  0.638062
348                           categorical__msa_40380.0    -0.634394  0.634394
237                           categorical__msa_29820.0     0.628776  0.628776
532  categorical__seller_name_CALIBER HOME LOANS, INC.     0.623215  0.623215
573      categorical__servicer_name_QUICKEN LOANS, LLC    -0.612355  0.612355
94                            categorical__msa_17410.0     0.605225  0.605225
267                           categorical__msa_33124.0     0.597325  0.597325
480                     categorical__property_state_HI     0.595878  0.595878
219                           categorical__msa_28740.0     0.586403  0.586403
0                                numeric__credit_score    -0.565120  0.565120